version: '3.6'
services:
  scudo-webapp:
    image: marcomazzoni/quorum-react-app:latest
    networks:
      config_quorum_net:
        ipv4_address: '172.13.0.10'
    ports:
      - 5001:80

  proxy:
    image: jwilder/nginx-proxy
    networks:
      config_quorum_net:
        ipv4_address: '172.13.0.11'
    ports:
      - 81:80

networks:
  config_quorum_net:
    external: true
